### ISSUE TITLE
How to ovewrite the default modal style on theme?

### ISSUE THREAD

**Issue by adrianKielbasaDomeny** [mautic/plugin-focus#1]
How to ovewrite default modal style on theme?
I try use theme https://github.com/Custonext/mautic-theme, but this theme doesn't ovewrite default style modal.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
